# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-24 20:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 24, 20, 58, 53, 779941, tzinfo=utc), editable=False, verbose_name='Date created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='Has been sent'),
            preserve_default=False,
        ),
    ]
