# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_auto_20170724_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='title',
        ),
        migrations.AddField(
            model_name='quote',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='quote',
            name='client',
            field=models.CharField(default='Unknown', max_length=255, verbose_name='Client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
