# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20170726_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='sent_date',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Date sent'),
        ),
    ]
