# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_quote_sent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='sent',
            field=models.BooleanField(default=False, verbose_name='Has been sent'),
        ),
    ]
