# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_auto_20170727_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='modified',
        ),
    ]
