# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_remove_quote_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='title',
            field=models.CharField(default=False, max_length=300, verbose_name='Title'),
        ),
    ]
