# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_quote_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='pm',
            field=models.IntegerField(default=15, verbose_name='Project Manager Percentage'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Title'),
        ),
    ]
