# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_quote_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='conditions',
            field=models.CharField(choices=[('Catalyst Standard Terms', 'Catalyst Standard Terms'), ('G-Cloud Terms', 'G-Cloud Terms')], default='Catalyst Standard Terms', max_length=250),
        ),
    ]
