# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0011_quote_conditions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='address',
            new_name='address_1',
        ),
        migrations.AddField(
            model_name='quote',
            name='address_2',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
