# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0012_auto_20170731_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='intro_text',
            field=models.CharField(default=0, max_length=500, verbose_name='Introduction Text'),
        ),
    ]
