# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0013_quote_intro_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='intro_text',
            field=models.CharField(blank=True, max_length=500, verbose_name='Introduction Text'),
        ),
    ]
