# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0014_auto_20170731_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='intro_text',
            field=models.CharField(default='text', max_length=500, verbose_name='Introduction Text'),
        ),
    ]
